version: '3'

services:
  gitlab-instance:
    container_name: gitlab-instance
    image: "gitlab/gitlab-ce:latest"
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:80'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['initial_root_password'] = 'secret_pass'
        registry['enable'] = true
        registry_external_url 'http://localhost:4567'
        puma['socket'] = '/opt/gitlab/var/puma/gitlab.socket'
    ports:
      - '80:80'
      - '2222:22'
      - '4567:4567'
      - '443:443'
    volumes:
      - '/gitlab-instance-config:/etc/gitlab'
      - '/gitlab-instance-logs:/var/log/gitlab'
      - '/gitlab-instance-data:/var/opt/gitlab'
    networks:
      - gitlab-network
  
  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    restart: always
    hostname: gitlab_runner
    depends_on:
      - gitlab-instance
    volumes: 
      - './gitlab-runner-config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab-network

networks:
  gitlab-network:
  




